export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Experience } from './experience/Experience'
export { default as Skills } from './skills/Skills'
export { default as Work } from './work/Work'
