name: setup-node
description: "Setup Node.js for the build"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
